#!/bin/sh
#
# start/stop the mon server
#
# You probably want to set the path to include
# nothing but local filesystems.
#
# chkconfig: 2345 99 10
# description: mon system monitoring daemon
# processname: mon
# config: /etc/mon/mon.cf
# pidfile: /var/run/mon.pid
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
    start)
	echo -n "Starting mon daemon: "
	daemon /usr/lib/mon/mon -c /etc/mon/mon.cf
	echo
	touch /var/lock/subsys/mon
	;;
    stop)
	echo -n "Stopping mon daemon: "
	killproc mon
	echo
	rm -f /var/lock/subsys/mon
	;;
    status)
    	status mon
	;;
    restart)
    	killall -HUP mon
	;;
    *)
    	echo "Usage: mon {start|stop|status|restart}"
	exit 1
esac

exit 0
